name: "Cache Solana Build Artifacts"
description: "Internal composite action for Solana caching logic"

inputs:
  cache-path:
    description: "Paths to cache"
    required: true
  fail-on-cache-miss:
    default: "false"
    description: "If true, fails if cache is missing"
    required: false

outputs:
  cache-status:
    description: "Descriptive cache status: 'primary', 'fallback', or 'not-found'"
    value: ${{ steps.determine-cache-status.outputs.status }}

runs:
  using: "composite"
  steps:
    - uses: "actions/cache@v4"
      id: "cache-step"
      with:
        fail-on-cache-miss: ${{ inputs.fail-on-cache-miss }}
        path: ${{ inputs.cache-path }}

        # Primary cache key composed of:
        #   1. Hash of Anchor.toml
        #   1. Hash of Cargo.toml
        #   3. Hash of all program files
        key: |
          anchor-build-${{ hashFiles('Anchor.toml') }}-${{ hashFiles('Cargo.lock') }}-${{ hashFiles('programs/**/*') }}

        # `restore-keys` is a terrible name and should be renamed to `backup-keys`:
        # See https://stackoverflow.com/a/79575296/3873510
        # See https://github.com/actions/cache/issues/1590
        restore-keys: |
          anchor-build-${{ hashFiles('Anchor.toml') }}-${{ hashFiles('Cargo.lock') }}
          anchor-build-${{ hashFiles('Anchor.toml') }}

    # Interpret cache-hit output into three-part cache-status.
    # See https://github.com/actions/cache/issues/1566
    - name: "Determine cache status"
      id: determine-cache-status
      shell: bash
      run: | # shell
        if [[ "${{ steps.cache-step.outputs.cache-hit }}" == "true" ]]; then
          echo "status=primary" >> $GITHUB_OUTPUT
        elif [[ "${{ steps.cache-step.outputs.cache-hit }}" == "false" ]]; then
          echo "status=fallback" >> $GITHUB_OUTPUT
        else
          echo "status=not-found" >> $GITHUB_OUTPUT
        fi
