name: "Measure test coverage for a Forge project"

on:
  workflow_call:
    inputs:
      cache-path:
        default: |
          cache
          node_modules
          out
          out-optimized
        required: false
        type: "string"

      match-path:
        required: true
        type: "string"

      # This flag allows coverage with via-ir enabled for the "minimum amount of optimization" necessary.
      via-ir-minimum:
        default: false
        required: false
        type: "boolean"

    secrets:
      CODECOV_TOKEN:
        required: true
      MAINNET_RPC_URL:
        required: false

jobs:
  forge-coverage:
    env:
      MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"

      - name: "Restore the cached build"
        uses: "sablier-labs/reusable-workflows/.github/actions/cache@ci/proper-cache"
        with:
          cache-path: ${{ inputs.cache-path }}
          fail-on-cache-miss: true

      - name: "Generate the coverage report"
        run: | # shell
          if [ "${{ inputs.via-ir-minimum }}" == "true" ]; then
            forge coverage --match-path "${{ inputs.match-path }}" --report lcov --ir-minimum
          else
            forge coverage --match-path "${{ inputs.match-path }}" --report lcov
          fi

      - name: "Upload coverage report to Codecov"
        uses: "codecov/codecov-action@v4"
        with:
          files: "./lcov.info"
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: "Add summary"
        run: | # shell
          echo "## Forge Coverage result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Uploaded to Codecov" >> $GITHUB_STEP_SUMMARY
